### ISSUE TITLE
https://www.github.com/ instead git@github.com

### ISSUE THREAD

**Issue by duchonic** [morandg/zephyr-blinky-advanced#2]
FATAL ERROR: command exited with status 128: fetch -f --tags -- git@github.com:zephyrproject-rtos/zephyr 'refs/heads/*:refs/west/*'

I changed git@github.com to https://www.github.com within the west.yml, 
also for the readme git@github.com:morandg/z... i changed the command to https://

Havent used github for a while, maybe it's my fault, maybe we have to change documentation and the west.yml?

**Comment by duchonic** [comment]
worked fine with my linux laptop and github credentials

**Comment by morandg** [comment]
Hi @duchonic, thanks for reporting this issue. It's better if we can clone the project without having a github account, will change to https.
